import { action, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import type { Id } from "./_generated/dataModel";
import { internal } from "./_generated/api";
import { computeCognitiveScore, computeFinalIndependenceScore } from "./domain/scoring";

const DEMO_CONFIRMATION = "SEED_JEE_DEMO";
const DEMO_CLASSROOM_NAME = "[JEE Demo] 2026 Full-System Test Cohort";
const DEMO_ASSIGNMENT_PREFIX = "[JEE Demo]";
const DEMO_STUDENT_EMAIL_PREFIX = "jee.demo.student.";
const DEMO_LECTURER_EMAIL = "jee.demo.lecturer@cogait.local";
const DEFAULT_ORGANIZATION_NAME = "Default Organization";

type Subject = "Physics" | "Chemistry" | "Math";
type Difficulty = "easy" | "medium" | "hard";
type AssignmentStatus = "completed" | "in_progress" | "not_started";

type QuestionSeed = {
  questionText: string;
  subject: Subject;
  topic: string;
  subtopic?: string;
  difficulty: Difficulty;
  mcqOptions: string[];
  correctOption: "A" | "B" | "C" | "D";
  correctAnswer: string;
};

type AssignmentSeed = {
  title: string;
  subject: Subject;
  chapter: string;
  difficulty: "easy" | "medium" | "hard" | "mixed";
  description: string;
  instructions: string;
  timeLimitMinutes: number;
  questions: QuestionSeed[];
};

type ScenarioPattern = {
  key: string;
  status: AssignmentStatus;
  helpBase: number;
  maxHelpLevel: number;
  accuracyBias: number;
  reasoningBase: number;
  elapsedRatio: number;
  overtimeRatio: number;
  violationBias: number;
  copyPasteBias: number;
};

const STUDENT_NAMES = [
  "Aarav Sharma",
  "Diya Patel",
  "Ishaan Gupta",
  "Ananya Singh",
  "Vivaan Mehta",
  "Aadhya Iyer",
  "Advait Reddy",
  "Kavya Nair",
  "Reyansh Verma",
  "Myra Joshi",
  "Arjun Kulkarni",
  "Siya Malhotra",
  "Krish Bansal",
  "Riya Chawla",
  "Pranav Sinha",
  "Meera Saxena",
  "Yash Thakur",
  "Tara Kapoor",
  "Lakshya Rao",
  "Navya Deshmukh",
];

const SCENARIO_PATTERNS: ScenarioPattern[] = [
  {
    key: "confident_fast_solver",
    status: "completed",
    helpBase: 0,
    maxHelpLevel: 1,
    accuracyBias: 0.92,
    reasoningBase: 180,
    elapsedRatio: 0.62,
    overtimeRatio: 0,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "methodical_but_slow",
    status: "completed",
    helpBase: 1,
    maxHelpLevel: 2,
    accuracyBias: 0.82,
    reasoningBase: 210,
    elapsedRatio: 0.92,
    overtimeRatio: 0.08,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "high_help_dependency",
    status: "completed",
    helpBase: 4,
    maxHelpLevel: 4,
    accuracyBias: 0.66,
    reasoningBase: 95,
    elapsedRatio: 1.06,
    overtimeRatio: 0.18,
    violationBias: 0.05,
    copyPasteBias: 0.04,
  },
  {
    key: "conceptual_gap_cluster",
    status: "completed",
    helpBase: 3,
    maxHelpLevel: 3,
    accuracyBias: 0.44,
    reasoningBase: 110,
    elapsedRatio: 0.97,
    overtimeRatio: 0.11,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "careless_fast_attempt",
    status: "completed",
    helpBase: 1,
    maxHelpLevel: 1,
    accuracyBias: 0.51,
    reasoningBase: 80,
    elapsedRatio: 0.48,
    overtimeRatio: 0,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "improving_reflective",
    status: "completed",
    helpBase: 2,
    maxHelpLevel: 2,
    accuracyBias: 0.76,
    reasoningBase: 190,
    elapsedRatio: 0.84,
    overtimeRatio: 0.04,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "anxious_overtime",
    status: "in_progress",
    helpBase: 2,
    maxHelpLevel: 3,
    accuracyBias: 0.58,
    reasoningBase: 145,
    elapsedRatio: 1.12,
    overtimeRatio: 0.25,
    violationBias: 0.03,
    copyPasteBias: 0,
  },
  {
    key: "copy_paste_risk",
    status: "in_progress",
    helpBase: 3,
    maxHelpLevel: 4,
    accuracyBias: 0.49,
    reasoningBase: 70,
    elapsedRatio: 0.71,
    overtimeRatio: 0.03,
    violationBias: 0.18,
    copyPasteBias: 0.24,
  },
  {
    key: "nearly_independent",
    status: "completed",
    helpBase: 1,
    maxHelpLevel: 2,
    accuracyBias: 0.87,
    reasoningBase: 170,
    elapsedRatio: 0.78,
    overtimeRatio: 0,
    violationBias: 0,
    copyPasteBias: 0,
  },
  {
    key: "disengaged_partial",
    status: "not_started",
    helpBase: 0,
    maxHelpLevel: 0,
    accuracyBias: 0.2,
    reasoningBase: 0,
    elapsedRatio: 0,
    overtimeRatio: 0,
    violationBias: 0,
    copyPasteBias: 0,
  },
];

const ASSIGNMENT_CATALOG: AssignmentSeed[] = [
  {
    title: `${DEMO_ASSIGNMENT_PREFIX} Physics Mechanics Stress Test`,
    subject: "Physics",
    chapter: "Kinematics and Newton's Laws",
    difficulty: "medium",
    description: "Mixed JEE-style mechanics questions covering vectors, acceleration graphs, pulleys, and friction.",
    instructions: "Write your core approach before final answers. Avoid jumping directly to formulas.",
    timeLimitMinutes: 70,
    questions: [
      {
        questionText: "A particle starts from rest and moves with acceleration a(t)=4t+2 m/s^2. Find its speed after 3 seconds.",
        subject: "Physics",
        topic: "Kinematics",
        subtopic: "Variable Acceleration",
        difficulty: "medium",
        mcqOptions: ["18 m/s", "21 m/s", "24 m/s", "27 m/s"],
        correctOption: "C",
        correctAnswer: "24 m/s",
      },
      {
        questionText: "Two blocks of 2 kg and 3 kg are connected by a light string on a frictionless table. A horizontal force of 20 N acts on the 3 kg block. Find the tension in the string.",
        subject: "Physics",
        topic: "Newton's Laws",
        subtopic: "Connected Bodies",
        difficulty: "medium",
        mcqOptions: ["6 N", "8 N", "10 N", "12 N"],
        correctOption: "B",
        correctAnswer: "8 N",
      },
      {
        questionText: "A body is projected vertically upward with speed 30 m/s. Taking g=10 m/s^2, find the maximum height reached.",
        subject: "Physics",
        topic: "Kinematics",
        subtopic: "Vertical Motion",
        difficulty: "easy",
        mcqOptions: ["35 m", "40 m", "45 m", "50 m"],
        correctOption: "C",
        correctAnswer: "45 m",
      },
      {
        questionText: "A 5 kg block remains at rest on a rough horizontal surface until a 15 N force is applied. If the limiting friction is 20 N, what is the frictional force acting now?",
        subject: "Physics",
        topic: "Friction",
        subtopic: "Static Friction",
        difficulty: "easy",
        mcqOptions: ["0 N", "5 N", "15 N", "20 N"],
        correctOption: "C",
        correctAnswer: "15 N",
      },
      {
        questionText: "A block slides down a smooth incline of angle 30 degrees. What is its acceleration? Take g=10 m/s^2.",
        subject: "Physics",
        topic: "Newton's Laws",
        subtopic: "Inclined Plane",
        difficulty: "easy",
        mcqOptions: ["2.5 m/s^2", "5 m/s^2", "7.5 m/s^2", "10 m/s^2"],
        correctOption: "B",
        correctAnswer: "5 m/s^2",
      },
      {
        questionText: "The displacement-time graph of a body is x=t^3-6t^2+9t. Find the time when instantaneous velocity is zero other than t=0.",
        subject: "Physics",
        topic: "Kinematics",
        subtopic: "Velocity from Graphs",
        difficulty: "hard",
        mcqOptions: ["1 s", "2 s", "3 s", "4 s"],
        correctOption: "C",
        correctAnswer: "3 s",
      },
      {
        questionText: "A 4 kg and a 6 kg mass are connected over a frictionless pulley. Find the magnitude of acceleration. Take g=10 m/s^2.",
        subject: "Physics",
        topic: "Newton's Laws",
        subtopic: "Atwood Machine",
        difficulty: "medium",
        mcqOptions: ["1 m/s^2", "2 m/s^2", "3 m/s^2", "4 m/s^2"],
        correctOption: "B",
        correctAnswer: "2 m/s^2",
      },
      {
        questionText: "A car moves on a circular track of radius 50 m with speed 10 m/s. Find centripetal acceleration.",
        subject: "Physics",
        topic: "Circular Motion",
        subtopic: "Centripetal Acceleration",
        difficulty: "easy",
        mcqOptions: ["1 m/s^2", "2 m/s^2", "4 m/s^2", "5 m/s^2"],
        correctOption: "B",
        correctAnswer: "2 m/s^2",
      },
    ],
  },
  {
    title: `${DEMO_ASSIGNMENT_PREFIX} Physics Electrostatics Diagnostic`,
    subject: "Physics",
    chapter: "Electrostatics and Current Electricity",
    difficulty: "hard",
    description: "Field, potential, capacitance, and resistance combination questions at JEE Main/Advanced level.",
    instructions: "State the principle used before calculations. Use symmetry arguments wherever possible.",
    timeLimitMinutes: 75,
    questions: [
      {
        questionText: "Two equal charges +q are placed 2 m apart. Find the electric field at the midpoint.",
        subject: "Physics",
        topic: "Electrostatics",
        subtopic: "Electric Field",
        difficulty: "easy",
        mcqOptions: ["Zero", "kq", "2kq", "kq/2"],
        correctOption: "A",
        correctAnswer: "Zero",
      },
      {
        questionText: "A capacitor of 4 microfarad is connected to a 12 V battery. Find the energy stored.",
        subject: "Physics",
        topic: "Capacitance",
        subtopic: "Energy in Capacitor",
        difficulty: "medium",
        mcqOptions: ["144 microjoule", "288 microjoule", "432 microjoule", "576 microjoule"],
        correctOption: "B",
        correctAnswer: "288 microjoule",
      },
      {
        questionText: "Three resistors 2 ohm, 3 ohm, and 6 ohm are connected in parallel. Find the equivalent resistance.",
        subject: "Physics",
        topic: "Current Electricity",
        subtopic: "Parallel Combination",
        difficulty: "medium",
        mcqOptions: ["1 ohm", "2 ohm", "3 ohm", "6 ohm"],
        correctOption: "A",
        correctAnswer: "1 ohm",
      },
      {
        questionText: "The potential at a point due to a charge +5 microcoulomb placed 3 m away is approximately:",
        subject: "Physics",
        topic: "Electrostatics",
        subtopic: "Electric Potential",
        difficulty: "medium",
        mcqOptions: ["5 kV", "10 kV", "15 kV", "20 kV"],
        correctOption: "C",
        correctAnswer: "15 kV",
      },
      {
        questionText: "A wire of resistance 8 ohm is stretched to double its length. Assuming volume constant, the new resistance is:",
        subject: "Physics",
        topic: "Current Electricity",
        subtopic: "Resistivity",
        difficulty: "hard",
        mcqOptions: ["8 ohm", "12 ohm", "16 ohm", "32 ohm"],
        correctOption: "D",
        correctAnswer: "32 ohm",
      },
      {
        questionText: "A charge moves from point A to B in an electric field and loses 20 J of potential energy. Work done by the field is:",
        subject: "Physics",
        topic: "Electrostatics",
        subtopic: "Work and Energy",
        difficulty: "easy",
        mcqOptions: ["-20 J", "0 J", "10 J", "20 J"],
        correctOption: "D",
        correctAnswer: "20 J",
      },
      {
        questionText: "Two capacitors 3 microfarad and 6 microfarad are in series. Equivalent capacitance is:",
        subject: "Physics",
        topic: "Capacitance",
        subtopic: "Series Combination",
        difficulty: "easy",
        mcqOptions: ["1 microfarad", "2 microfarad", "3 microfarad", "9 microfarad"],
        correctOption: "B",
        correctAnswer: "2 microfarad",
      },
      {
        questionText: "A battery of emf 12 V and internal resistance 1 ohm is connected to a 5 ohm external resistor. Current in the circuit is:",
        subject: "Physics",
        topic: "Current Electricity",
        subtopic: "Internal Resistance",
        difficulty: "medium",
        mcqOptions: ["1 A", "1.5 A", "2 A", "2.5 A"],
        correctOption: "C",
        correctAnswer: "2 A",
      },
    ],
  },
  {
    title: `${DEMO_ASSIGNMENT_PREFIX} Chemistry Thermodynamics and Equilibrium`,
    subject: "Chemistry",
    chapter: "Thermodynamics and Ionic Equilibrium",
    difficulty: "medium",
    description: "Numerical-heavy chemistry set focused on delta H, Gibbs energy, pH, buffers, and solubility.",
    instructions: "Track sign conventions carefully. Mention the governing chemical relation before substitution.",
    timeLimitMinutes: 65,
    questions: [
      {
        questionText: "For an exothermic reaction, the sign of delta H is:",
        subject: "Chemistry",
        topic: "Thermodynamics",
        subtopic: "Enthalpy Change",
        difficulty: "easy",
        mcqOptions: ["Positive", "Negative", "Zero", "Cannot be predicted"],
        correctOption: "B",
        correctAnswer: "Negative",
      },
      {
        questionText: "If delta G is negative for a process at constant temperature and pressure, the process is:",
        subject: "Chemistry",
        topic: "Thermodynamics",
        subtopic: "Gibbs Free Energy",
        difficulty: "easy",
        mcqOptions: ["Spontaneous", "Non-spontaneous", "At equilibrium", "Impossible"],
        correctOption: "A",
        correctAnswer: "Spontaneous",
      },
      {
        questionText: "The pH of 0.001 M HCl solution is:",
        subject: "Chemistry",
        topic: "Ionic Equilibrium",
        subtopic: "pH of Strong Acid",
        difficulty: "easy",
        mcqOptions: ["1", "2", "3", "4"],
        correctOption: "C",
        correctAnswer: "3",
      },
      {
        questionText: "At equilibrium, the rate of forward reaction is compared to reverse reaction as:",
        subject: "Chemistry",
        topic: "Chemical Equilibrium",
        subtopic: "Dynamic Equilibrium",
        difficulty: "easy",
        mcqOptions: ["Greater", "Smaller", "Equal", "Zero"],
        correctOption: "C",
        correctAnswer: "Equal",
      },
      {
        questionText: "For the reaction N2 + 3H2 <-> 2NH3, if pressure is increased, equilibrium shifts towards:",
        subject: "Chemistry",
        topic: "Chemical Equilibrium",
        subtopic: "Le Chatelier Principle",
        difficulty: "medium",
        mcqOptions: ["Reactants", "Products", "No shift", "Depends on catalyst"],
        correctOption: "B",
        correctAnswer: "Products",
      },
      {
        questionText: "The relation delta G = delta H - T delta S suggests spontaneity is favored at high temperature when delta H > 0 and delta S is:",
        subject: "Chemistry",
        topic: "Thermodynamics",
        subtopic: "Entropy and Spontaneity",
        difficulty: "hard",
        mcqOptions: ["Negative", "Positive", "Zero", "Undefined"],
        correctOption: "B",
        correctAnswer: "Positive",
      },
      {
        questionText: "The pOH of a solution with pH = 9 at 25 degree Celsius is:",
        subject: "Chemistry",
        topic: "Ionic Equilibrium",
        subtopic: "pH-pOH Relation",
        difficulty: "easy",
        mcqOptions: ["3", "5", "7", "9"],
        correctOption: "B",
        correctAnswer: "5",
      },
      {
        questionText: "The buffer solution resists change in pH on addition of:",
        subject: "Chemistry",
        topic: "Ionic Equilibrium",
        subtopic: "Buffer Solutions",
        difficulty: "medium",
        mcqOptions: ["Small acid/base only", "Only water", "Only salt", "Only indicator"],
        correctOption: "A",
        correctAnswer: "Small acid/base only",
      },
    ],
  },
  {
    title: `${DEMO_ASSIGNMENT_PREFIX} Chemistry Organic Reaction Paths`,
    subject: "Chemistry",
    chapter: "General Organic Chemistry and Hydrocarbons",
    difficulty: "mixed",
    description: "Mechanism recognition, acidity/basicity, resonance, and stereochemical reasoning for JEE aspirants.",
    instructions: "Justify each step with inductive, resonance, or mechanistic logic before choosing an option.",
    timeLimitMinutes: 70,
    questions: [
      {
        questionText: "Among the following, the most acidic compound is:",
        subject: "Chemistry",
        topic: "General Organic Chemistry",
        subtopic: "Acidity Order",
        difficulty: "medium",
        mcqOptions: ["Ethanol", "Phenol", "Ethyne", "Ethane"],
        correctOption: "B",
        correctAnswer: "Phenol",
      },
      {
        questionText: "The electrophile in nitration of benzene is:",
        subject: "Chemistry",
        topic: "Hydrocarbons",
        subtopic: "Electrophilic Substitution",
        difficulty: "easy",
        mcqOptions: ["NO2+", "NO3-", "HNO3", "SO3"],
        correctOption: "A",
        correctAnswer: "NO2+",
      },
      {
        questionText: "The major product of addition of HBr to propene in absence of peroxide is:",
        subject: "Chemistry",
        topic: "Hydrocarbons",
        subtopic: "Markovnikov Addition",
        difficulty: "medium",
        mcqOptions: ["1-bromopropane", "2-bromopropane", "Propane", "Propan-1-ol"],
        correctOption: "B",
        correctAnswer: "2-bromopropane",
      },
      {
        questionText: "The hybridization of carbon atoms in benzene is:",
        subject: "Chemistry",
        topic: "General Organic Chemistry",
        subtopic: "Hybridization",
        difficulty: "easy",
        mcqOptions: ["sp", "sp2", "sp3", "dsp2"],
        correctOption: "B",
        correctAnswer: "sp2",
      },
      {
        questionText: "The stability of carbocations is generally:",
        subject: "Chemistry",
        topic: "General Organic Chemistry",
        subtopic: "Reactive Intermediates",
        difficulty: "medium",
        mcqOptions: ["1° > 2° > 3°", "3° > 2° > 1°", "2° > 1° > 3°", "All equal"],
        correctOption: "B",
        correctAnswer: "3° > 2° > 1°",
      },
      {
        questionText: "Which effect explains the acidity of carboxylic acids being higher than alcohols?",
        subject: "Chemistry",
        topic: "General Organic Chemistry",
        subtopic: "Resonance Stabilization",
        difficulty: "hard",
        mcqOptions: ["Hyperconjugation", "Resonance", "Steric effect", "Hydrogen bonding only"],
        correctOption: "B",
        correctAnswer: "Resonance",
      },
      {
        questionText: "Bromine water is decolorized by ethene because ethene undergoes:",
        subject: "Chemistry",
        topic: "Hydrocarbons",
        subtopic: "Unsaturation Test",
        difficulty: "easy",
        mcqOptions: ["Substitution", "Addition", "Elimination", "Polymerization"],
        correctOption: "B",
        correctAnswer: "Addition",
      },
      {
        questionText: "In SN1 reaction, the rate-determining step is:",
        subject: "Chemistry",
        topic: "General Organic Chemistry",
        subtopic: "Reaction Mechanisms",
        difficulty: "hard",
        mcqOptions: ["Nucleophile attack", "Carbocation formation", "Proton transfer", "Solvent ionization only"],
        correctOption: "B",
        correctAnswer: "Carbocation formation",
      },
    ],
  },
]
